//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Housing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.ApartmentCategories = new HashSet<ApartmentCategory>();
        }
    
        public string ApartmentID { get; set; }
        public string ApartmentNumber { get; set; }
        public string CategoryID { get; set; }
        public string BuildingID { get; set; }
        public string VillageID { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> RoomOccupancy { get; set; }
        public Nullable<int> TotalRoomOccupancy { get; set; }
        public string RoomAvailable { get; set; }
        public string OccupancyType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentCategory> ApartmentCategories { get; set; }
    }
}
