//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Housing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public string ApplicantID { get; set; }
        public string UserID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string ApplicantsEmail { get; set; }
        public string MobileNum { get; set; }
        public System.DateTime DOB { get; set; }
        public string PPSNumber { get; set; }
        public string Nationality { get; set; }
        public string CountryOfBirth { get; set; }
        public string Gender { get; set; }
        public string MartialStatus { get; set; }
        public string ParentGardianName { get; set; }
        public string ParentGardianEmail { get; set; }
        public string ParentGardianTelephone { get; set; }
        public string College { get; set; }
        public string Course { get; set; }
        public string CourseYear { get; set; }
        public string Department { get; set; }
        public string VillagePreference { get; set; }
        public string VillagePreference2 { get; set; }
        public string VillagePreference3 { get; set; }
        public string ApartmentCategoryPref1 { get; set; }
        public string ApartmentCategoryPref2 { get; set; }
        public string ApartmentCategoryPref3 { get; set; }
        public string ApplicationStatus { get; set; }
        public string ApartmentOfferStatus { get; set; }
        public string ApartmentRejectCount { get; set; }
    
        public virtual User User { get; set; }
    }
}
