//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Housing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public string BuildingID { get; set; }
        public string BuildingName { get; set; }
        public string VillageID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateSurveyed { get; set; }
        public Nullable<System.DateTime> NextSurveyDue { get; set; }
    
        public virtual Village Village { get; set; }
    }
}
