//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestHousing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public string RequestID { get; set; }
        public string UserID { get; set; }
        public string BuildingID { get; set; }
        public string BuildingName { get; set; }
        public string ProblemDescription { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<System.DateTime> RequestCompletionDate { get; set; }
        public string EmployeeID { get; set; }
        public string AssignedTo { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
    }
}
